[package]
name = "rust-lib-wasm"
version = "0.1.0"
authors = ["Gero Posmyk-Leinemann <gero.posmyk-leinemann@typefox.io>"]
edition = "2018"

[lib]
crate-type = ["cdylib"]

[dependencies]
rust-lib = { path = "../rust-lib" }

wasm-bindgen = "0.2.64"
thiserror = "1.0.20"
js-sys = "0.3.41"
